# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses


@dataclasses.dataclass()
class Author:
    id: int
    name: str
    bio: str | None


@dataclasses.dataclass()
class Job:
    id: int
    errors: str
    cast: str | None
    list: list[str] | None
    id_2: int | None
    dict: dict[str, int] | None
