# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import dataclasses
from collections.abc import AsyncIterator, Iterator, Sequence
from typing import cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from modern import errors, models


ADD_JOB = """-- name: add_job \\:one
INSERT INTO jobs (errors, "cast") VALUES (:p1, :p2) RETURNING id, errors, "cast", list, id_2, dict
"""


CREATE_AUTHOR = """-- name: create_author \\:one
INSERT INTO authors (name, bio) VALUES (:p1, :p2) RETURNING id, name, bio
"""


DELETE_AUTHOR = """-- name: delete_author \\:exec
DELETE FROM authors WHERE id = :p1
"""


GET_AUTHORS_BY_ID = """-- name: get_authors_by_id \\:batchone
SELECT id, name, bio FROM authors WHERE id = :p1
"""


@dataclasses.dataclass()
class GetAuthorsByIDParams:
    id: int


LIST_AUTHORS = """-- name: list_authors \\:many
SELECT id, name, bio FROM authors ORDER BY name
"""


LIST_JOBS_BY_DICT = """-- name: list_jobs_by_dict \\:many
SELECT id, errors, "cast", list, id_2, dict FROM jobs WHERE dict = :p1
"""


LIST_JOBS_IN_RANGE = """-- name: list_jobs_in_range \\:many
SELECT id, errors, "cast", list, id_2, dict FROM jobs WHERE id > :p1 AND id < :p2
"""


PROBE_JOBS = """-- name: probe_jobs \\:many
SELECT id, id_2, id, list, dict FROM jobs WHERE list = :p1 AND id > :p2 AND id < :p3 AND id_2 = :p4
"""


@dataclasses.dataclass()
class ProbeJobsRow:
    id: int
    id_2: int | None
    id_3: int
    list: list[str] | None
    dict: dict[str, int] | None


class Querier:
    _conn: sqlalchemy.engine.Connection | sqlalchemy.orm.Session

    def __init__(self, conn: sqlalchemy.engine.Connection | sqlalchemy.orm.Session):
        self._conn = conn

    def add_job(self, *, errors_: str, cast_: str | None) -> models.Job | None:
        with errors._wrap_errors("add_job"):
            row = self._conn.execute(sqlalchemy.text(ADD_JOB), {"p1": errors_, "p2": cast_}).first()
            if row is None:
                return None
            return models.Job(
                id=cast(int, row[0]),
                errors=cast(str, row[1]),
                cast=cast(str | None, row[2]),
                list=cast(list[str] | None, row[3]),
                id_2=cast(int | None, row[4]),
                dict=cast(dict[str, int] | None, row[5]),
            )

    def create_author(self, *, name: str, bio: str | None) -> models.Author | None:
        """Insert an author."""
        with errors._wrap_errors("create_author"):
            row = self._conn.execute(sqlalchemy.text(CREATE_AUTHOR), {"p1": name, "p2": bio}).first()
            if row is None:
                return None
            return models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
            )

    def delete_author(self, *, id: int) -> None:
        with errors._wrap_errors("delete_author"):
            self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})

    def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> Iterator[models.Author | None]:
        with errors._wrap_errors("get_authors_by_id"):
            for a in arg:
                row = self._conn.execute(sqlalchemy.text(GET_AUTHORS_BY_ID), {"p1": a.id}).first()
                if row is None:
                    yield None
                else:
                    yield models.Author(
                        id=cast(int, row[0]),
                        name=cast(str, row[1]),
                        bio=cast(str | None, row[2]),
                    )

    def list_authors(self) -> Iterator[models.Author]:
        with errors._wrap_errors("list_authors"):
            result = self._conn.execute(sqlalchemy.text(LIST_AUTHORS))
            for row in result:
                yield models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                    bio=cast(str | None, row[2]),
                )

    def list_jobs_by_dict(self, *, dict_: dict[str, int] | None) -> Iterator[models.Job]:
        with errors._wrap_errors("list_jobs_by_dict"):
            result = self._conn.execute(sqlalchemy.text(LIST_JOBS_BY_DICT), {"p1": dict_})
            for row in result:
                yield models.Job(
                    id=cast(int, row[0]),
                    errors=cast(str, row[1]),
                    cast=cast(str | None, row[2]),
                    list=cast(list[str] | None, row[3]),
                    id_2=cast(int | None, row[4]),
                    dict=cast(dict[str, int] | None, row[5]),
                )

    def list_jobs_in_range(self, *, id: int, id_2: int) -> Iterator[models.Job]:
        with errors._wrap_errors("list_jobs_in_range"):
            result = self._conn.execute(sqlalchemy.text(LIST_JOBS_IN_RANGE), {"p1": id, "p2": id_2})
            for row in result:
                yield models.Job(
                    id=cast(int, row[0]),
                    errors=cast(str, row[1]),
                    cast=cast(str | None, row[2]),
                    list=cast(list[str] | None, row[3]),
                    id_2=cast(int | None, row[4]),
                    dict=cast(dict[str, int] | None, row[5]),
                )

    def probe_jobs(self, *, list_: list[str] | None, id: int, id_2: int, id_2_2: int | None) -> Iterator[ProbeJobsRow]:
        with errors._wrap_errors("probe_jobs"):
            result = self._conn.execute(sqlalchemy.text(PROBE_JOBS), {
                "p1": list_,
                "p2": id,
                "p3": id_2,
                "p4": id_2_2,
            })
            for row in result:
                yield ProbeJobsRow(
                    id=cast(int, row[0]),
                    id_2=cast(int | None, row[1]),
                    id_3=cast(int, row[2]),
                    list=cast(list[str] | None, row[3]),
                    dict=cast(dict[str, int] | None, row[4]),
                )


class AsyncQuerier:
    _conn: sqlalchemy.ext.asyncio.AsyncConnection | sqlalchemy.ext.asyncio.AsyncSession

    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection | sqlalchemy.ext.asyncio.AsyncSession):
        self._conn = conn

    async def add_job(self, *, errors_: str, cast_: str | None) -> models.Job | None:
        with errors._wrap_errors("add_job"):
            row = (await self._conn.execute(sqlalchemy.text(ADD_JOB), {"p1": errors_, "p2": cast_})).first()
            if row is None:
                return None
            return models.Job(
                id=cast(int, row[0]),
                errors=cast(str, row[1]),
                cast=cast(str | None, row[2]),
                list=cast(list[str] | None, row[3]),
                id_2=cast(int | None, row[4]),
                dict=cast(dict[str, int] | None, row[5]),
            )

    async def create_author(self, *, name: str, bio: str | None) -> models.Author | None:
        """Insert an author."""
        with errors._wrap_errors("create_author"):
            row = (await self._conn.execute(sqlalchemy.text(CREATE_AUTHOR), {"p1": name, "p2": bio})).first()
            if row is None:
                return None
            return models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
            )

    async def delete_author(self, *, id: int) -> None:
        with errors._wrap_errors("delete_author"):
            await self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})

    async def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> AsyncIterator[models.Author | None]:
        with errors._wrap_errors("get_authors_by_id"):
            for a in arg:
                row = (await self._conn.execute(sqlalchemy.text(GET_AUTHORS_BY_ID), {"p1": a.id})).first()
                if row is None:
                    yield None
                else:
                    yield models.Author(
                        id=cast(int, row[0]),
                        name=cast(str, row[1]),
                        bio=cast(str | None, row[2]),
                    )

    async def list_authors(self) -> AsyncIterator[models.Author]:
        with errors._wrap_errors("list_authors"):
            result = await self._conn.stream(sqlalchemy.text(LIST_AUTHORS))
            async for row in result:
                yield models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                    bio=cast(str | None, row[2]),
                )

    async def list_jobs_by_dict(self, *, dict_: dict[str, int] | None) -> AsyncIterator[models.Job]:
        with errors._wrap_errors("list_jobs_by_dict"):
            result = await self._conn.stream(sqlalchemy.text(LIST_JOBS_BY_DICT), {"p1": dict_})
            async for row in result:
                yield models.Job(
                    id=cast(int, row[0]),
                    errors=cast(str, row[1]),
                    cast=cast(str | None, row[2]),
                    list=cast(list[str] | None, row[3]),
                    id_2=cast(int | None, row[4]),
                    dict=cast(dict[str, int] | None, row[5]),
                )

    async def list_jobs_in_range(self, *, id: int, id_2: int) -> AsyncIterator[models.Job]:
        with errors._wrap_errors("list_jobs_in_range"):
            result = await self._conn.stream(sqlalchemy.text(LIST_JOBS_IN_RANGE), {"p1": id, "p2": id_2})
            async for row in result:
                yield models.Job(
                    id=cast(int, row[0]),
                    errors=cast(str, row[1]),
                    cast=cast(str | None, row[2]),
                    list=cast(list[str] | None, row[3]),
                    id_2=cast(int | None, row[4]),
                    dict=cast(dict[str, int] | None, row[5]),
                )

    async def probe_jobs(self, *, list_: list[str] | None, id: int, id_2: int, id_2_2: int | None) -> AsyncIterator[ProbeJobsRow]:
        with errors._wrap_errors("probe_jobs"):
            result = await self._conn.stream(sqlalchemy.text(PROBE_JOBS), {
                "p1": list_,
                "p2": id,
                "p3": id_2,
                "p4": id_2_2,
            })
            async for row in result:
                yield ProbeJobsRow(
                    id=cast(int, row[0]),
                    id_2=cast(int | None, row[1]),
                    id_3=cast(int, row[2]),
                    list=cast(list[str] | None, row[3]),
                    dict=cast(dict[str, int] | None, row[4]),
                )
