# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import enum
import pydantic


class BookStatus(enum.StrEnum):
    DRAFT = "draft"
    IN_PRINT = "in-print"
    OUT_OF_PRINT = "out_of_print"


class Author(pydantic.BaseModel):
    id: int
    name: str
    bio: str | None
    created_at: pydantic.AwareDatetime


class Book(pydantic.BaseModel):
    id: int
    author_id: int
    title: str
    status: BookStatus
