# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import pydantic
from collections.abc import AsyncIterator, Iterator, Sequence
from typing import Any, Protocol, cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from library_modern import errors, models


CREATE_AUTHOR = """-- name: create_author \\:one
INSERT INTO authors (name, bio) VALUES (:p1, :p2) RETURNING id, name, bio, created_at
"""


CREATE_AUTHOR_AT = """-- name: create_author_at \\:one
INSERT INTO authors (name, created_at) VALUES (:p1, :p2) RETURNING id, name, bio, created_at
"""


CREATE_AUTHORS = """-- name: create_authors \\:copyfrom
INSERT INTO authors (name, bio) VALUES (:p1, :p2)
"""


class CreateAuthorsParams(pydantic.BaseModel):
    name: str
    bio: str | None


CREATE_BOOK = """-- name: create_book \\:one
INSERT INTO books (author_id, title) VALUES (:p1, :p2) RETURNING id, author_id, title, status
"""


CREATE_BOOKS = """-- name: create_books \\:batchexec
INSERT INTO books (author_id, title, status) VALUES (:p1, :p2, :p3)
"""


class CreateBooksParams(pydantic.BaseModel):
    author_id: int
    title: str
    status: models.BookStatus


GET_AUTHORS_BY_ID = """-- name: get_authors_by_id \\:batchone
SELECT id, name, bio, created_at FROM authors WHERE id = :p1
"""


class GetAuthorsByIDParams(pydantic.BaseModel):
    id: int


GET_BOOK_WITH_AUTHOR = """-- name: get_book_with_author \\:one
SELECT books.id, books.author_id, books.title, books.status, authors.id, authors.name, authors.bio, authors.created_at
FROM books JOIN authors ON authors.id = books.author_id
WHERE books.id = :p1
"""


class GetBookWithAuthorRow(pydantic.BaseModel):
    books: models.Book
    authors: models.Author


INSERT_AUTHORS_RETURNING = """-- name: insert_authors_returning \\:batchone
INSERT INTO authors (name) VALUES (:p1) RETURNING id, name, bio, created_at
"""


class InsertAuthorsReturningParams(pydantic.BaseModel):
    name: str


LIST_AUTHORS = """-- name: list_authors \\:many
SELECT id, name, bio, created_at FROM authors ORDER BY name
"""


LIST_BOOKS_BY_AUTHOR = """-- name: list_books_by_author \\:batchmany
SELECT id, author_id, title, status FROM books WHERE author_id = :p1 ORDER BY id
"""


class ListBooksByAuthorParams(pydantic.BaseModel):
    author_id: int


SET_BOOK_TITLE = """-- name: set_book_title \\:exec
UPDATE books SET title = :p2 WHERE id = :p1
"""


class QuerierProtocol(Protocol):
    def create_author(self, *, name: str, bio: str | None) -> models.Author | None: ...

    def create_author_at(self, *, name: str, created_at: pydantic.AwareDatetime) -> models.Author | None: ...

    def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int: ...

    def create_book(self, *, author_id: int, title: str) -> models.Book | None: ...

    def create_books(self, arg: Sequence[CreateBooksParams]) -> None: ...

    def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> Iterator[models.Author | None]: ...

    def get_book_with_author(self, *, id: int) -> GetBookWithAuthorRow | None: ...

    def insert_authors_returning(self, arg: Sequence[InsertAuthorsReturningParams]) -> Iterator[models.Author | None]: ...

    def list_authors(self) -> Iterator[models.Author]: ...

    def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> Iterator[list[models.Book]]: ...

    def set_book_title(self, *, id: int, title: str) -> None: ...


class AsyncQuerierProtocol(Protocol):
    async def create_author(self, *, name: str, bio: str | None) -> models.Author | None: ...

    async def create_author_at(self, *, name: str, created_at: pydantic.AwareDatetime) -> models.Author | None: ...

    async def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int: ...

    async def create_book(self, *, author_id: int, title: str) -> models.Book | None: ...

    async def create_books(self, arg: Sequence[CreateBooksParams]) -> None: ...

    def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> AsyncIterator[models.Author | None]: ...

    async def get_book_with_author(self, *, id: int) -> GetBookWithAuthorRow | None: ...

    def insert_authors_returning(self, arg: Sequence[InsertAuthorsReturningParams]) -> AsyncIterator[models.Author | None]: ...

    def list_authors(self) -> AsyncIterator[models.Author]: ...

    def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> AsyncIterator[list[models.Book]]: ...

    async def set_book_title(self, *, id: int, title: str) -> None: ...


class Querier[T: sqlalchemy.engine.Connection | sqlalchemy.orm.Session]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    def create_author(self, *, name: str, bio: str | None) -> models.Author | None:
        """Create one author."""
        with errors._wrap_errors("create_author"):
            row = self._conn.execute(sqlalchemy.text(CREATE_AUTHOR), {"p1": name, "p2": bio}).first()
            if row is None:
                return None
            return models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
                created_at=cast(pydantic.AwareDatetime, row[3]),
            )

    def create_author_at(self, *, name: str, created_at: pydantic.AwareDatetime) -> models.Author | None:
        with errors._wrap_errors("create_author_at"):
            row = self._conn.execute(sqlalchemy.text(CREATE_AUTHOR_AT), {"p1": name, "p2": created_at}).first()
            if row is None:
                return None
            return models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
                created_at=cast(pydantic.AwareDatetime, row[3]),
            )

    def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int:
        with errors._wrap_errors("create_authors"):
            if not arg:
                return 0
            result = self._conn.execute(sqlalchemy.text(CREATE_AUTHORS), [{"p1": a.name, "p2": a.bio} for a in arg])
            return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount

    def create_book(self, *, author_id: int, title: str) -> models.Book | None:
        with errors._wrap_errors("create_book"):
            row = self._conn.execute(sqlalchemy.text(CREATE_BOOK), {"p1": author_id, "p2": title}).first()
            if row is None:
                return None
            return models.Book(
                id=cast(int, row[0]),
                author_id=cast(int, row[1]),
                title=cast(str, row[2]),
                status=cast(models.BookStatus, row[3]),
            )

    def create_books(self, arg: Sequence[CreateBooksParams]) -> None:
        with errors._wrap_errors("create_books"):
            if not arg:
                return None
            self._conn.execute(sqlalchemy.text(CREATE_BOOKS), [{"p1": a.author_id, "p2": a.title, "p3": a.status} for a in arg])

    def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> Iterator[models.Author | None]:
        with errors._wrap_errors("get_authors_by_id"):
            for a in arg:
                row = self._conn.execute(sqlalchemy.text(GET_AUTHORS_BY_ID), {"p1": a.id}).first()
                if row is None:
                    yield None
                else:
                    yield models.Author(
                        id=cast(int, row[0]),
                        name=cast(str, row[1]),
                        bio=cast(str | None, row[2]),
                        created_at=cast(pydantic.AwareDatetime, row[3]),
                    )

    def get_book_with_author(self, *, id: int) -> GetBookWithAuthorRow | None:
        with errors._wrap_errors("get_book_with_author"):
            row = self._conn.execute(sqlalchemy.text(GET_BOOK_WITH_AUTHOR), {"p1": id}).first()
            if row is None:
                return None
            return GetBookWithAuthorRow(
                books=models.Book(
                    id=cast(int, row[0]),
                    author_id=cast(int, row[1]),
                    title=cast(str, row[2]),
                    status=cast(models.BookStatus, row[3]),
                ),
                authors=models.Author(
                    id=cast(int, row[4]),
                    name=cast(str, row[5]),
                    bio=cast(str | None, row[6]),
                    created_at=cast(pydantic.AwareDatetime, row[7]),
                ),
            )

    def insert_authors_returning(self, arg: Sequence[InsertAuthorsReturningParams]) -> Iterator[models.Author | None]:
        with errors._wrap_errors("insert_authors_returning"):
            for a in arg:
                row = self._conn.execute(sqlalchemy.text(INSERT_AUTHORS_RETURNING), {"p1": a.name}).first()
                if row is None:
                    yield None
                else:
                    yield models.Author(
                        id=cast(int, row[0]),
                        name=cast(str, row[1]),
                        bio=cast(str | None, row[2]),
                        created_at=cast(pydantic.AwareDatetime, row[3]),
                    )

    def list_authors(self) -> Iterator[models.Author]:
        with errors._wrap_errors("list_authors"):
            result = self._conn.execute(sqlalchemy.text(LIST_AUTHORS))
            for row in result:
                yield models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                    bio=cast(str | None, row[2]),
                    created_at=cast(pydantic.AwareDatetime, row[3]),
                )

    def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> Iterator[list[models.Book]]:
        with errors._wrap_errors("list_books_by_author"):
            for a in arg:
                yield [models.Book(
                    id=cast(int, row[0]),
                    author_id=cast(int, row[1]),
                    title=cast(str, row[2]),
                    status=cast(models.BookStatus, row[3]),
                ) for row in self._conn.execute(sqlalchemy.text(LIST_BOOKS_BY_AUTHOR), {"p1": a.author_id})]

    def set_book_title(self, *, id: int, title: str) -> None:
        with errors._wrap_errors("set_book_title"):
            self._conn.execute(sqlalchemy.text(SET_BOOK_TITLE), {"p1": id, "p2": title})


class AsyncQuerier[T: sqlalchemy.ext.asyncio.AsyncConnection | sqlalchemy.ext.asyncio.AsyncSession]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    async def create_author(self, *, name: str, bio: str | None) -> models.Author | None:
        """Create one author."""
        with errors._wrap_errors("create_author"):
            row = (await self._conn.execute(sqlalchemy.text(CREATE_AUTHOR), {"p1": name, "p2": bio})).first()
            if row is None:
                return None
            return models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
                created_at=cast(pydantic.AwareDatetime, row[3]),
            )

    async def create_author_at(self, *, name: str, created_at: pydantic.AwareDatetime) -> models.Author | None:
        with errors._wrap_errors("create_author_at"):
            row = (await self._conn.execute(sqlalchemy.text(CREATE_AUTHOR_AT), {"p1": name, "p2": created_at})).first()
            if row is None:
                return None
            return models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
                created_at=cast(pydantic.AwareDatetime, row[3]),
            )

    async def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int:
        with errors._wrap_errors("create_authors"):
            if not arg:
                return 0
            result = await self._conn.execute(sqlalchemy.text(CREATE_AUTHORS), [{"p1": a.name, "p2": a.bio} for a in arg])
            return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount

    async def create_book(self, *, author_id: int, title: str) -> models.Book | None:
        with errors._wrap_errors("create_book"):
            row = (await self._conn.execute(sqlalchemy.text(CREATE_BOOK), {"p1": author_id, "p2": title})).first()
            if row is None:
                return None
            return models.Book(
                id=cast(int, row[0]),
                author_id=cast(int, row[1]),
                title=cast(str, row[2]),
                status=cast(models.BookStatus, row[3]),
            )

    async def create_books(self, arg: Sequence[CreateBooksParams]) -> None:
        with errors._wrap_errors("create_books"):
            if not arg:
                return None
            await self._conn.execute(sqlalchemy.text(CREATE_BOOKS), [{"p1": a.author_id, "p2": a.title, "p3": a.status} for a in arg])

    async def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> AsyncIterator[models.Author | None]:
        with errors._wrap_errors("get_authors_by_id"):
            for a in arg:
                row = (await self._conn.execute(sqlalchemy.text(GET_AUTHORS_BY_ID), {"p1": a.id})).first()
                if row is None:
                    yield None
                else:
                    yield models.Author(
                        id=cast(int, row[0]),
                        name=cast(str, row[1]),
                        bio=cast(str | None, row[2]),
                        created_at=cast(pydantic.AwareDatetime, row[3]),
                    )

    async def get_book_with_author(self, *, id: int) -> GetBookWithAuthorRow | None:
        with errors._wrap_errors("get_book_with_author"):
            row = (await self._conn.execute(sqlalchemy.text(GET_BOOK_WITH_AUTHOR), {"p1": id})).first()
            if row is None:
                return None
            return GetBookWithAuthorRow(
                books=models.Book(
                    id=cast(int, row[0]),
                    author_id=cast(int, row[1]),
                    title=cast(str, row[2]),
                    status=cast(models.BookStatus, row[3]),
                ),
                authors=models.Author(
                    id=cast(int, row[4]),
                    name=cast(str, row[5]),
                    bio=cast(str | None, row[6]),
                    created_at=cast(pydantic.AwareDatetime, row[7]),
                ),
            )

    async def insert_authors_returning(self, arg: Sequence[InsertAuthorsReturningParams]) -> AsyncIterator[models.Author | None]:
        with errors._wrap_errors("insert_authors_returning"):
            for a in arg:
                row = (await self._conn.execute(sqlalchemy.text(INSERT_AUTHORS_RETURNING), {"p1": a.name})).first()
                if row is None:
                    yield None
                else:
                    yield models.Author(
                        id=cast(int, row[0]),
                        name=cast(str, row[1]),
                        bio=cast(str | None, row[2]),
                        created_at=cast(pydantic.AwareDatetime, row[3]),
                    )

    async def list_authors(self) -> AsyncIterator[models.Author]:
        with errors._wrap_errors("list_authors"):
            result = await self._conn.stream(sqlalchemy.text(LIST_AUTHORS))
            async for row in result:
                yield models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                    bio=cast(str | None, row[2]),
                    created_at=cast(pydantic.AwareDatetime, row[3]),
                )

    async def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> AsyncIterator[list[models.Book]]:
        with errors._wrap_errors("list_books_by_author"):
            for a in arg:
                yield [models.Book(
                    id=cast(int, row[0]),
                    author_id=cast(int, row[1]),
                    title=cast(str, row[2]),
                    status=cast(models.BookStatus, row[3]),
                ) for row in await self._conn.execute(sqlalchemy.text(LIST_BOOKS_BY_AUTHOR), {"p1": a.author_id})]

    async def set_book_title(self, *, id: int, title: str) -> None:
        with errors._wrap_errors("set_book_title"):
            await self._conn.execute(sqlalchemy.text(SET_BOOK_TITLE), {"p1": id, "p2": title})
