# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses
import enum
from typing import Optional


class Mood(str, enum.Enum):
    """How someone feels.
Two values only."""
    HAPPY = "happy"
    SAD = "sad"


@dataclasses.dataclass()
class Author:
    """People who write books.
Second line with "quotes"."""
    id: int
    # first line
    # second line
    name: str
    mood: Optional[Mood]
