# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
from typing import Optional, Union, cast

import sqlalchemy
import sqlalchemy.orm

from db import models


GET_AUTHOR = """-- name: get_author \\:one
SELECT id, name, mood FROM authors
WHERE id = :p1 LIMIT 1
"""


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def get_author(self, *, id: int) -> Optional[models.Author]:
        row = self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id}).first()
        if row is None:
            return None
        return models.Author(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            mood=cast(Optional[models.Mood], row[2]),
        )
