# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import dataclasses
from typing import Any, Optional, Sequence, Union, cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from db import models


CREATE_AUTHORS = """-- name: create_authors \\:copyfrom
INSERT INTO authors (name, bio) VALUES (:p1, :p2)
"""


@dataclasses.dataclass()
class CreateAuthorsParams:
    name: str
    bio: Optional[str]


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int:
        if not arg:
            return 0
        result = self._conn.execute(sqlalchemy.text(CREATE_AUTHORS), [{"p1": a.name, "p2": a.bio} for a in arg])
        return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount


class AsyncQuerier:
    _conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]

    def __init__(self, conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]):
        self._conn = conn

    async def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int:
        if not arg:
            return 0
        result = await self._conn.execute(sqlalchemy.text(CREATE_AUTHORS), [{"p1": a.name, "p2": a.bio} for a in arg])
        return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount
