# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses
import enum


class Op(str, enum.Enum):
    """Operators with "quoted" names"""
    VALUE_1 = "="
    VALUE_2 = "<>"
    IN_PROGRESS = "in-progress"
    IN_PROGRESS_2 = "in_progress"
    VALUE_1ST = "1st"
    SAYHI = "say \"hi\""
    BACKSLASH = "back\\slash"


@dataclasses.dataclass()
class Rule:
    id: int
    op: Op
