# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses
import datetime
from typing import Any


@dataclasses.dataclass()
class Everything:
    id: int
    a_varchar: str
    a_charvar: str
    a_bpchar: str
    a_char: str
    a_name: str
    a_time: datetime.time
    a_timetz: datetime.time
    a_time_wo: datetime.time
    a_time_w: datetime.time
    a_ts: datetime.datetime
    a_tstz: datetime.datetime
    a_ts_wo: datetime.datetime
    a_ts_w: datetime.datetime
    a_json: Any
    a_jsonb: Any
