# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import dataclasses
import datetime
from typing import Any, Optional

import sqlalchemy

from db import models


CAST_ALIASES = """-- name: cast_aliases \\:one
SELECT
  :p1\\:\\:varchar AS v,
  :p2\\:\\:character varying AS cv,
  :p3\\:\\:bpchar AS bp,
  :p4\\:\\:name AS n,
  :p5\\:\\:time AS t,
  :p6\\:\\:timetz AS ttz,
  :p7\\:\\:timestamp AS ts,
  :p8\\:\\:timestamptz AS tstz,
  :p9\\:\\:pg_catalog.json AS j,
  :p10\\:\\:pg_catalog.jsonb AS jb
"""


@dataclasses.dataclass()
class CastAliasesParams:
    column_1: str
    column_2: str
    column_3: str
    column_4: str
    column_5: datetime.time
    column_6: datetime.time
    column_7: datetime.datetime
    column_8: datetime.datetime
    column_9: Any
    column_10: Any


@dataclasses.dataclass()
class CastAliasesRow:
    v: str
    cv: str
    bp: str
    n: str
    t: datetime.time
    ttz: datetime.time
    ts: datetime.datetime
    tstz: datetime.datetime
    j: Any
    jb: Any


GET_EVERYTHING = """-- name: get_everything \\:one
SELECT id, a_varchar, a_charvar, a_bpchar, a_char, a_name, a_time, a_timetz, a_time_wo, a_time_w, a_ts, a_tstz, a_ts_wo, a_ts_w, a_json, a_jsonb FROM everything WHERE id = :p1
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def cast_aliases(self, arg: CastAliasesParams) -> Optional[CastAliasesRow]:
        row = self._conn.execute(sqlalchemy.text(CAST_ALIASES), {
            "p1": arg.column_1,
            "p2": arg.column_2,
            "p3": arg.column_3,
            "p4": arg.column_4,
            "p5": arg.column_5,
            "p6": arg.column_6,
            "p7": arg.column_7,
            "p8": arg.column_8,
            "p9": arg.column_9,
            "p10": arg.column_10,
        }).first()
        if row is None:
            return None
        return CastAliasesRow(
            v=row[0],
            cv=row[1],
            bp=row[2],
            n=row[3],
            t=row[4],
            ttz=row[5],
            ts=row[6],
            tstz=row[7],
            j=row[8],
            jb=row[9],
        )

    def get_everything(self, *, id: int) -> Optional[models.Everything]:
        row = self._conn.execute(sqlalchemy.text(GET_EVERYTHING), {"p1": id}).first()
        if row is None:
            return None
        return models.Everything(
            id=row[0],
            a_varchar=row[1],
            a_charvar=row[2],
            a_bpchar=row[3],
            a_char=row[4],
            a_name=row[5],
            a_time=row[6],
            a_timetz=row[7],
            a_time_wo=row[8],
            a_time_w=row[9],
            a_ts=row[10],
            a_tstz=row[11],
            a_ts_wo=row[12],
            a_ts_w=row[13],
            a_json=row[14],
            a_jsonb=row[15],
        )
