# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
from typing import Any, Union, cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from querytest import models


DELETE_BAR_BY_ID = """-- name: delete_bar_by_id \\:execrows
DELETE FROM bar WHERE id = :p1
"""


DELETE_BAR_BY_ID_AND_NAME = """-- name: delete_bar_by_id_and_name \\:execrows
DELETE FROM bar
WHERE id = :p1
AND name1 = :p2
AND name2 = :p3
AND name3 = :p4
"""


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def delete_bar_by_id(self, *, id: int) -> int:
        result = self._conn.execute(sqlalchemy.text(DELETE_BAR_BY_ID), {"p1": id})
        return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount

    def delete_bar_by_id_and_name(self, *, id: int, name1: str, name2: str, name3: str) -> int:
        result = self._conn.execute(sqlalchemy.text(DELETE_BAR_BY_ID_AND_NAME), {
            "p1": id,
            "p2": name1,
            "p3": name2,
            "p4": name3,
        })
        return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount


class AsyncQuerier:
    _conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]

    def __init__(self, conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]):
        self._conn = conn

    async def delete_bar_by_id(self, *, id: int) -> int:
        result = await self._conn.execute(sqlalchemy.text(DELETE_BAR_BY_ID), {"p1": id})
        return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount

    async def delete_bar_by_id_and_name(self, *, id: int, name1: str, name2: str, name3: str) -> int:
        result = await self._conn.execute(sqlalchemy.text(DELETE_BAR_BY_ID_AND_NAME), {
            "p1": id,
            "p2": name1,
            "p3": name2,
            "p4": name3,
        })
        return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount
