# Code generated by sqlc. DO NOT EDIT.
# source: query.sql
from typing import Iterator, Union, cast

import sqlalchemy
import sqlalchemy.orm

from db import models


LIST_AUTHORS = """-- name: list_authors \\:many
SELECT id, name FROM authors
"""


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def list_authors(self) -> Iterator[models.Author]:
        result = self._conn.execute(sqlalchemy.text(LIST_AUTHORS))
        for row in result:
            yield models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
            )
