# Code generated by sqlc. DO NOT EDIT.
# source: query.sql
from typing import Iterator

import sqlalchemy

from db import models


LIST_AUTHORS = """-- name: list_authors \\:many
SELECT id, name FROM authors
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def list_authors(self) -> Iterator[models.Author]:
        result = self._conn.execute(sqlalchemy.text(LIST_AUTHORS))
        for row in result:
            yield models.Author(
                id=row[0],
                name=row[1],
            )
