# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: a.sql
from typing import Iterator, Optional, Union, cast

import sqlalchemy
import sqlalchemy.orm

from db import models


GET_USER = """-- name: get_user \\:one
SELECT name FROM things WHERE id = :p1
"""


LIST = """-- name: list \\:many
SELECT name FROM things
"""


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def get_user(self, *, id: int) -> Optional[str]:
        row = self._conn.execute(sqlalchemy.text(GET_USER), {"p1": id}).first()
        if row is None:
            return None
        return cast(str, row[0])

    def list_(self) -> Iterator[str]:
        result = self._conn.execute(sqlalchemy.text(LIST))
        for row in result:
            yield cast(str, row[0])
