# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: b.sql
from typing import Iterator, Optional, Union, cast

import sqlalchemy
import sqlalchemy.orm

from db import models


GET_USER = """-- name: get_user \\:one
SELECT id FROM things WHERE id = :p1
"""


LIST_ = """-- name: list_ \\:many
SELECT id FROM things
"""


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def get_user(self, *, id: int) -> Optional[int]:
        row = self._conn.execute(sqlalchemy.text(GET_USER), {"p1": id}).first()
        if row is None:
            return None
        return cast(int, row[0])

    def list_(self) -> Iterator[int]:
        result = self._conn.execute(sqlalchemy.text(LIST_))
        for row in result:
            yield cast(int, row[0])
