# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import dataclasses
from typing import AsyncIterator, Iterator, List, Optional, Sequence, Union, cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from classic import models


GET_AUTHOR_NAMES = """-- name: get_author_names \\:batchone
SELECT name FROM authors WHERE id = :p1
"""


@dataclasses.dataclass()
class GetAuthorNamesParams:
    id: int


GET_AUTHORS_BY_ID = """-- name: get_authors_by_id \\:batchone
SELECT id, name, bio FROM authors WHERE id = :p1
"""


@dataclasses.dataclass()
class GetAuthorsByIDParams:
    id: int


LIST_BOOK_TITLES = """-- name: list_book_titles \\:batchmany
SELECT id, title FROM books WHERE author_id = :p1 AND title LIKE :p2
"""


@dataclasses.dataclass()
class ListBookTitlesParams:
    author_id: int
    title: str


@dataclasses.dataclass()
class ListBookTitlesRow:
    id: int
    title: str


LIST_BOOKS_BY_AUTHOR = """-- name: list_books_by_author \\:batchmany
SELECT id, author_id, title FROM books WHERE author_id = :p1
"""


@dataclasses.dataclass()
class ListBooksByAuthorParams:
    author_id: int


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def get_author_names(self, arg: Sequence[GetAuthorNamesParams]) -> Iterator[Optional[str]]:
        for a in arg:
            row = self._conn.execute(sqlalchemy.text(GET_AUTHOR_NAMES), {"p1": a.id}).first()
            if row is None:
                yield None
            else:
                yield cast(str, row[0])

    def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> Iterator[Optional[models.Author]]:
        for a in arg:
            row = self._conn.execute(sqlalchemy.text(GET_AUTHORS_BY_ID), {"p1": a.id}).first()
            if row is None:
                yield None
            else:
                yield models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                    bio=cast(Optional[str], row[2]),
                )

    def list_book_titles(self, arg: Sequence[ListBookTitlesParams]) -> Iterator[List[ListBookTitlesRow]]:
        for a in arg:
            yield [ListBookTitlesRow(
                id=cast(int, row[0]),
                title=cast(str, row[1]),
            ) for row in self._conn.execute(sqlalchemy.text(LIST_BOOK_TITLES), {"p1": a.author_id, "p2": a.title})]

    def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> Iterator[List[models.Book]]:
        for a in arg:
            yield [models.Book(
                id=cast(int, row[0]),
                author_id=cast(int, row[1]),
                title=cast(str, row[2]),
            ) for row in self._conn.execute(sqlalchemy.text(LIST_BOOKS_BY_AUTHOR), {"p1": a.author_id})]


class AsyncQuerier:
    _conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]

    def __init__(self, conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]):
        self._conn = conn

    async def get_author_names(self, arg: Sequence[GetAuthorNamesParams]) -> AsyncIterator[Optional[str]]:
        for a in arg:
            row = (await self._conn.execute(sqlalchemy.text(GET_AUTHOR_NAMES), {"p1": a.id})).first()
            if row is None:
                yield None
            else:
                yield cast(str, row[0])

    async def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> AsyncIterator[Optional[models.Author]]:
        for a in arg:
            row = (await self._conn.execute(sqlalchemy.text(GET_AUTHORS_BY_ID), {"p1": a.id})).first()
            if row is None:
                yield None
            else:
                yield models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                    bio=cast(Optional[str], row[2]),
                )

    async def list_book_titles(self, arg: Sequence[ListBookTitlesParams]) -> AsyncIterator[List[ListBookTitlesRow]]:
        for a in arg:
            yield [ListBookTitlesRow(
                id=cast(int, row[0]),
                title=cast(str, row[1]),
            ) for row in await self._conn.execute(sqlalchemy.text(LIST_BOOK_TITLES), {"p1": a.author_id, "p2": a.title})]

    async def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> AsyncIterator[List[models.Book]]:
        for a in arg:
            yield [models.Book(
                id=cast(int, row[0]),
                author_id=cast(int, row[1]),
                title=cast(str, row[2]),
            ) for row in await self._conn.execute(sqlalchemy.text(LIST_BOOKS_BY_AUTHOR), {"p1": a.author_id})]
