# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses
from typing import List, Optional


@dataclasses.dataclass()
class Grid:
    id: int
    matrix: List[List[int]]
    cube: Optional[List[List[List[int]]]]
    tags: Optional[List[str]]
