# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
from typing import List, Optional, Union, cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from db import models


CREATE_GRID = """-- name: create_grid \\:exec
INSERT INTO grids (matrix, cube, tags) VALUES (:p1, :p2, :p3)
"""


GET_GRID = """-- name: get_grid \\:one
SELECT id, matrix, cube, tags FROM grids WHERE id = :p1
"""


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def create_grid(self, *, matrix: List[List[int]], cube: Optional[List[List[List[int]]]], tags: Optional[List[str]]) -> None:
        self._conn.execute(sqlalchemy.text(CREATE_GRID), {"p1": matrix, "p2": cube, "p3": tags})

    def get_grid(self, *, id: int) -> Optional[models.Grid]:
        row = self._conn.execute(sqlalchemy.text(GET_GRID), {"p1": id}).first()
        if row is None:
            return None
        return models.Grid(
            id=cast(int, row[0]),
            matrix=cast(List[List[int]], row[1]),
            cube=cast(Optional[List[List[List[int]]]], row[2]),
            tags=cast(Optional[List[str]], row[3]),
        )


class AsyncQuerier:
    _conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]

    def __init__(self, conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]):
        self._conn = conn

    async def create_grid(self, *, matrix: List[List[int]], cube: Optional[List[List[List[int]]]], tags: Optional[List[str]]) -> None:
        await self._conn.execute(sqlalchemy.text(CREATE_GRID), {"p1": matrix, "p2": cube, "p3": tags})

    async def get_grid(self, *, id: int) -> Optional[models.Grid]:
        row = (await self._conn.execute(sqlalchemy.text(GET_GRID), {"p1": id})).first()
        if row is None:
            return None
        return models.Grid(
            id=cast(int, row[0]),
            matrix=cast(List[List[int]], row[1]),
            cube=cast(Optional[List[List[List[int]]]], row[2]),
            tags=cast(Optional[List[str]], row[3]),
        )
