# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
from typing import List, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from db import models


CREATE_GRID = """-- name: create_grid \\:exec
INSERT INTO grids (matrix, cube, tags) VALUES (:p1, :p2, :p3)
"""


GET_GRID = """-- name: get_grid \\:one
SELECT id, matrix, cube, tags FROM grids WHERE id = :p1
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_grid(self, *, matrix: List[List[int]], cube: Optional[List[List[List[int]]]], tags: Optional[List[str]]) -> None:
        self._conn.execute(sqlalchemy.text(CREATE_GRID), {"p1": matrix, "p2": cube, "p3": tags})

    def get_grid(self, *, id: int) -> Optional[models.Grid]:
        row = self._conn.execute(sqlalchemy.text(GET_GRID), {"p1": id}).first()
        if row is None:
            return None
        return models.Grid(
            id=row[0],
            matrix=row[1],
            cube=row[2],
            tags=row[3],
        )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_grid(self, *, matrix: List[List[int]], cube: Optional[List[List[List[int]]]], tags: Optional[List[str]]) -> None:
        await self._conn.execute(sqlalchemy.text(CREATE_GRID), {"p1": matrix, "p2": cube, "p3": tags})

    async def get_grid(self, *, id: int) -> Optional[models.Grid]:
        row = (await self._conn.execute(sqlalchemy.text(GET_GRID), {"p1": id})).first()
        if row is None:
            return None
        return models.Grid(
            id=row[0],
            matrix=row[1],
            cube=row[2],
            tags=row[3],
        )
