# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import pydantic
from typing import Optional


class Author(pydantic.BaseModel):
    id: int
    name: str


class Book(pydantic.BaseModel):
    id: int
    author_id: int
    title: str
    isbn: Optional[str]
