# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
from typing import Optional, Union, cast

import my_lib
import sqlalchemy
import sqlalchemy.orm

from db import models


GET_MEMBER_BY_EMAIL = """-- name: get_member_by_email \\:one
SELECT id, email, nickname FROM members WHERE email = :p1
"""


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def get_member_by_email(self, *, email: my_lib.CIText) -> Optional[models.Member]:
        row = self._conn.execute(sqlalchemy.text(GET_MEMBER_BY_EMAIL), {"p1": email}).first()
        if row is None:
            return None
        return models.Member(
            id=cast(int, row[0]),
            email=cast(my_lib.CIText, row[1]),
            alias=cast(str, row[2]),
        )
