# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
from typing import Optional

import my_lib
import sqlalchemy

from db import models


GET_MEMBER_BY_EMAIL = """-- name: get_member_by_email \\:one
SELECT id, email, nickname FROM members WHERE email = :p1
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def get_member_by_email(self, *, email: my_lib.CIText) -> Optional[models.Member]:
        row = self._conn.execute(sqlalchemy.text(GET_MEMBER_BY_EMAIL), {"p1": email}).first()
        if row is None:
            return None
        return models.Member(
            id=row[0],
            email=row[1],
            alias=row[2],
        )
