# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: events.sql
import decimal
import uuid
from typing import Iterator, List, Optional, Union, cast

import my_lib
import my_lib.types
import sqlalchemy
import sqlalchemy.orm

from db import models


CREATE_EVENT = """-- name: create_event \\:one
INSERT INTO events (payload, extra) VALUES (:p1, :p2) RETURNING id, payload, extra, history, score, rank
"""


LIST_EVENTS_BY_RANK = """-- name: list_events_by_rank \\:many
SELECT id, payload, extra, history, score, rank FROM events WHERE rank > :p1 AND rank < :p2
"""


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def create_event(self, *, payload: my_lib.types.Payload, extra: Optional[my_lib.types.Payload]) -> Optional[models.Event]:
        row = self._conn.execute(sqlalchemy.text(CREATE_EVENT), {"p1": payload, "p2": extra}).first()
        if row is None:
            return None
        return models.Event(
            id=cast(int, row[0]),
            payload=cast(my_lib.types.Payload, row[1]),
            extra=cast(Optional[my_lib.types.Payload], row[2]),
            history=cast(Optional[List[my_lib.types.Payload]], row[3]),
            score=cast(my_lib.Box[decimal.Decimal], row[4]),
            rank=cast(dict[str, uuid.UUID], row[5]),
        )

    def list_events_by_rank(self, *, rank: dict[str, uuid.UUID], rank_2: dict[str, uuid.UUID]) -> Iterator[models.Event]:
        result = self._conn.execute(sqlalchemy.text(LIST_EVENTS_BY_RANK), {"p1": rank, "p2": rank_2})
        for row in result:
            yield models.Event(
                id=cast(int, row[0]),
                payload=cast(my_lib.types.Payload, row[1]),
                extra=cast(Optional[my_lib.types.Payload], row[2]),
                history=cast(Optional[List[my_lib.types.Payload]], row[3]),
                score=cast(my_lib.Box[decimal.Decimal], row[4]),
                rank=cast(dict[str, uuid.UUID], row[5]),
            )
