# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: events.sql
from typing import Optional

import my_lib.types
import sqlalchemy

from db import models


CREATE_EVENT = """-- name: create_event \\:one
INSERT INTO events (payload, extra) VALUES (:p1, :p2) RETURNING id, payload, extra, history
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def create_event(self, *, payload: my_lib.types.Payload, extra: Optional[my_lib.types.Payload]) -> Optional[models.Event]:
        row = self._conn.execute(sqlalchemy.text(CREATE_EVENT), {"p1": payload, "p2": extra}).first()
        if row is None:
            return None
        return models.Event(
            id=row[0],
            payload=row[1],
            extra=row[2],
            history=row[3],
        )
