# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses
import decimal
import uuid
from typing import List, Optional
from uuid import UUID

import my_ids
import my_lib
import my_lib.types


@dataclasses.dataclass()
class Author:
    id: UUID
    name: str
    avatar: bytes


@dataclasses.dataclass()
class Event:
    id: int
    payload: my_lib.types.Payload
    extra: Optional[my_lib.types.Payload]
    history: Optional[List[my_lib.types.Payload]]
    score: my_lib.Box[decimal.Decimal]
    rank: dict[str, uuid.UUID]


@dataclasses.dataclass()
class User:
    id: my_ids.UserId
    org_id: my_ids.Id
    extra: Optional[my_lib.types.Payload]
