# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: users.sql
from typing import Iterator, Optional, Union, cast
from uuid import UUID

import my_ids
import my_lib.types
import sqlalchemy
import sqlalchemy.orm

from db import models


GET_AUTHOR = """-- name: get_author \\:one
SELECT id, name, avatar FROM authors WHERE id = :p1
"""


GET_USER = """-- name: get_user \\:one
SELECT id, org_id, extra FROM users WHERE id = :p1
"""


LIST_USERS_BY_ORG = """-- name: list_users_by_org \\:many
SELECT id, org_id, extra FROM users WHERE org_id = :p1
"""


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def get_author(self, *, id: UUID) -> Optional[models.Author]:
        row = self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id}).first()
        if row is None:
            return None
        return models.Author(
            id=cast(UUID, row[0]),
            name=cast(str, row[1]),
            avatar=cast(bytes, row[2]),
        )

    def get_user(self, *, id: my_ids.UserId) -> Optional[models.User]:
        row = self._conn.execute(sqlalchemy.text(GET_USER), {"p1": id}).first()
        if row is None:
            return None
        return models.User(
            id=cast(my_ids.UserId, row[0]),
            org_id=cast(my_ids.Id, row[1]),
            extra=cast(Optional[my_lib.types.Payload], row[2]),
        )

    def list_users_by_org(self, *, org_id: my_ids.Id) -> Iterator[models.User]:
        result = self._conn.execute(sqlalchemy.text(LIST_USERS_BY_ORG), {"p1": org_id})
        for row in result:
            yield models.User(
                id=cast(my_ids.UserId, row[0]),
                org_id=cast(my_ids.Id, row[1]),
                extra=cast(Optional[my_lib.types.Payload], row[2]),
            )
