# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses
from typing import Optional


@dataclasses.dataclass()
class Author:
    id: int
    name: str
    bio: Optional[str]


@dataclasses.dataclass()
class Job:
    id: int
    errors: str
    cast: Optional[str]
