# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import dataclasses
from typing import AsyncIterator, Iterator, Optional, Sequence, Union, cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from classic import errors, models


ADD_JOB = """-- name: add_job \\:one
INSERT INTO jobs (errors, "cast") VALUES (:p1, :p2) RETURNING id, errors, "cast"
"""


CREATE_AUTHOR = """-- name: create_author \\:one
INSERT INTO authors (name, bio) VALUES (:p1, :p2) RETURNING id, name, bio
"""


DELETE_AUTHOR = """-- name: delete_author \\:exec
DELETE FROM authors WHERE id = :p1
"""


GET_AUTHORS_BY_ID = """-- name: get_authors_by_id \\:batchone
SELECT id, name, bio FROM authors WHERE id = :p1
"""


@dataclasses.dataclass()
class GetAuthorsByIDParams:
    id: int


LIST_AUTHORS = """-- name: list_authors \\:many
SELECT id, name, bio FROM authors ORDER BY name
"""


LIST_JOBS_IN_RANGE = """-- name: list_jobs_in_range \\:many
SELECT id, errors, "cast" FROM jobs WHERE id > :p1 AND id < :p2
"""


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def add_job(self, *, errors_: str, cast_: Optional[str]) -> Optional[models.Job]:
        with errors._wrap_errors("add_job"):
            row = self._conn.execute(sqlalchemy.text(ADD_JOB), {"p1": errors_, "p2": cast_}).first()
            if row is None:
                return None
            return models.Job(
                id=cast(int, row[0]),
                errors=cast(str, row[1]),
                cast=cast(Optional[str], row[2]),
            )

    def create_author(self, *, name: str, bio: Optional[str]) -> Optional[models.Author]:
        """Insert an author."""
        with errors._wrap_errors("create_author"):
            row = self._conn.execute(sqlalchemy.text(CREATE_AUTHOR), {"p1": name, "p2": bio}).first()
            if row is None:
                return None
            return models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(Optional[str], row[2]),
            )

    def delete_author(self, *, id: int) -> None:
        with errors._wrap_errors("delete_author"):
            self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})

    def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> Iterator[Optional[models.Author]]:
        with errors._wrap_errors("get_authors_by_id"):
            for a in arg:
                row = self._conn.execute(sqlalchemy.text(GET_AUTHORS_BY_ID), {"p1": a.id}).first()
                if row is None:
                    yield None
                else:
                    yield models.Author(
                        id=cast(int, row[0]),
                        name=cast(str, row[1]),
                        bio=cast(Optional[str], row[2]),
                    )

    def list_authors(self) -> Iterator[models.Author]:
        with errors._wrap_errors("list_authors"):
            result = self._conn.execute(sqlalchemy.text(LIST_AUTHORS))
            for row in result:
                yield models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                    bio=cast(Optional[str], row[2]),
                )

    def list_jobs_in_range(self, *, id: int, id_2: int) -> Iterator[models.Job]:
        with errors._wrap_errors("list_jobs_in_range"):
            result = self._conn.execute(sqlalchemy.text(LIST_JOBS_IN_RANGE), {"p1": id, "p2": id_2})
            for row in result:
                yield models.Job(
                    id=cast(int, row[0]),
                    errors=cast(str, row[1]),
                    cast=cast(Optional[str], row[2]),
                )


class AsyncQuerier:
    _conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]

    def __init__(self, conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]):
        self._conn = conn

    async def add_job(self, *, errors_: str, cast_: Optional[str]) -> Optional[models.Job]:
        with errors._wrap_errors("add_job"):
            row = (await self._conn.execute(sqlalchemy.text(ADD_JOB), {"p1": errors_, "p2": cast_})).first()
            if row is None:
                return None
            return models.Job(
                id=cast(int, row[0]),
                errors=cast(str, row[1]),
                cast=cast(Optional[str], row[2]),
            )

    async def create_author(self, *, name: str, bio: Optional[str]) -> Optional[models.Author]:
        """Insert an author."""
        with errors._wrap_errors("create_author"):
            row = (await self._conn.execute(sqlalchemy.text(CREATE_AUTHOR), {"p1": name, "p2": bio})).first()
            if row is None:
                return None
            return models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(Optional[str], row[2]),
            )

    async def delete_author(self, *, id: int) -> None:
        with errors._wrap_errors("delete_author"):
            await self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})

    async def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> AsyncIterator[Optional[models.Author]]:
        with errors._wrap_errors("get_authors_by_id"):
            for a in arg:
                row = (await self._conn.execute(sqlalchemy.text(GET_AUTHORS_BY_ID), {"p1": a.id})).first()
                if row is None:
                    yield None
                else:
                    yield models.Author(
                        id=cast(int, row[0]),
                        name=cast(str, row[1]),
                        bio=cast(Optional[str], row[2]),
                    )

    async def list_authors(self) -> AsyncIterator[models.Author]:
        with errors._wrap_errors("list_authors"):
            result = await self._conn.stream(sqlalchemy.text(LIST_AUTHORS))
            async for row in result:
                yield models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                    bio=cast(Optional[str], row[2]),
                )

    async def list_jobs_in_range(self, *, id: int, id_2: int) -> AsyncIterator[models.Job]:
        with errors._wrap_errors("list_jobs_in_range"):
            result = await self._conn.stream(sqlalchemy.text(LIST_JOBS_IN_RANGE), {"p1": id, "p2": id_2})
            async for row in result:
                yield models.Job(
                    id=cast(int, row[0]),
                    errors=cast(str, row[1]),
                    cast=cast(Optional[str], row[2]),
                )
