# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import datetime
import enum
import pydantic


class BookStatus(enum.StrEnum):
    """Lifecycle of a book.
"Out of print" books stay listed."""
    DRAFT = "draft"
    IN_PRINT = "in-print"
    OUT_OF_PRINT = "out_of_print"
    VALUE_4 = "="


class Author(pydantic.BaseModel):
    """People who write books."""
    id: int
    name: str
    bio: str | None
    created_at: pydantic.AwareDatetime


class Book(pydantic.BaseModel):
    id: int
    author_id: int
    title: str
    status: BookStatus
    # First published.
    # NULL until the book is released.
    from_: datetime.date | None
    tags: list[str] | None
