# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import datetime
import pydantic
from collections.abc import AsyncIterator, Iterator, Sequence
from typing import Any, Protocol, cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from db import errors, models


COUNT_AUTHORS = """-- name: count_authors \\:one
SELECT count(*) FROM authors
"""


CREATE_AUTHOR = """-- name: create_author \\:one
INSERT INTO authors (name, bio) VALUES (:p1, :p2) RETURNING id, name, bio, created_at
"""


CREATE_AUTHORS = """-- name: create_authors \\:copyfrom
INSERT INTO authors (name, bio) VALUES (:p1, :p2)
"""


class CreateAuthorsParams(pydantic.BaseModel):
    name: str
    bio: str | None


CREATE_BOOKS = """-- name: create_books \\:batchexec
INSERT INTO books (author_id, title, status, "from") VALUES (:p1, :p2, :p3, :p4)
"""


class CreateBooksParams(pydantic.BaseModel):
    author_id: int
    title: str
    status: models.BookStatus
    from_: datetime.date | None


DELETE_AUTHOR = """-- name: delete_author \\:execrows
DELETE FROM authors WHERE id = :p1
"""


GET_AUTHOR = """-- name: get_author \\:one
SELECT id, name, bio, created_at FROM authors WHERE id = :p1
"""


GET_AUTHORS_BY_ID = """-- name: get_authors_by_id \\:batchone
SELECT id, name, bio, created_at FROM authors WHERE id = :p1
"""


class GetAuthorsByIDParams(pydantic.BaseModel):
    id: int


GET_BOOK_WITH_AUTHOR = """-- name: get_book_with_author \\:one
SELECT books.id, books.author_id, books.title, books.status, books."from", books.tags, authors.id, authors.name, authors.bio, authors.created_at
FROM books JOIN authors ON authors.id = books.author_id
WHERE books.id = :p1
"""


class GetBookWithAuthorRow(pydantic.BaseModel):
    books: models.Book
    authors: models.Author


LIST_AUTHORS = """-- name: list_authors \\:many
SELECT id, name, bio, created_at FROM authors ORDER BY name
"""


LIST_BOOKS_BY_AUTHOR = """-- name: list_books_by_author \\:batchmany
SELECT id, author_id, title, status, "from", tags FROM books WHERE author_id = :p1 ORDER BY id
"""


class ListBooksByAuthorParams(pydantic.BaseModel):
    author_id: int


LIST_BOOKS_BY_STATUS = """-- name: list_books_by_status \\:many
SELECT books.id, books.title, books."from", authors.name AS author_name
FROM books JOIN authors ON authors.id = books.author_id
WHERE books.status = :p1 AND books.author_id = :p2\\:\\:bigint
"""


class ListBooksByStatusRow(pydantic.BaseModel):
    id: int
    title: str
    from_: datetime.date | None
    author_name: str


class QuerierProtocol(Protocol):
    def count_authors(self) -> int | None: ...

    def create_author(self, *, name: str, bio: str | None) -> models.Author | None: ...

    def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int: ...

    def create_books(self, arg: Sequence[CreateBooksParams]) -> None: ...

    def delete_author(self, *, id: int) -> int: ...

    def get_author(self, *, id: int) -> models.Author | None: ...

    def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> Iterator[models.Author | None]: ...

    def get_book_with_author(self, *, id: int) -> GetBookWithAuthorRow | None: ...

    def list_authors(self) -> Iterator[models.Author]: ...

    def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> Iterator[list[models.Book]]: ...

    def list_books_by_status(self, *, status: models.BookStatus, class_: int) -> Iterator[ListBooksByStatusRow]: ...


class AsyncQuerierProtocol(Protocol):
    async def count_authors(self) -> int | None: ...

    async def create_author(self, *, name: str, bio: str | None) -> models.Author | None: ...

    async def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int: ...

    async def create_books(self, arg: Sequence[CreateBooksParams]) -> None: ...

    async def delete_author(self, *, id: int) -> int: ...

    async def get_author(self, *, id: int) -> models.Author | None: ...

    def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> AsyncIterator[models.Author | None]: ...

    async def get_book_with_author(self, *, id: int) -> GetBookWithAuthorRow | None: ...

    def list_authors(self) -> AsyncIterator[models.Author]: ...

    def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> AsyncIterator[list[models.Book]]: ...

    def list_books_by_status(self, *, status: models.BookStatus, class_: int) -> AsyncIterator[ListBooksByStatusRow]: ...


class Querier[T: sqlalchemy.engine.Connection | sqlalchemy.orm.Session]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    def count_authors(self) -> int | None:
        with errors._wrap_errors("count_authors"):
            row = self._conn.execute(sqlalchemy.text(COUNT_AUTHORS)).first()
            if row is None:
                return None
            return cast(int, row[0])

    def create_author(self, *, name: str, bio: str | None) -> models.Author | None:
        """Create one author."""
        with errors._wrap_errors("create_author"):
            row = self._conn.execute(sqlalchemy.text(CREATE_AUTHOR), {"p1": name, "p2": bio}).first()
            if row is None:
                return None
            return models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
                created_at=cast(pydantic.AwareDatetime, row[3]),
            )

    def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int:
        with errors._wrap_errors("create_authors"):
            if not arg:
                return 0
            result = self._conn.execute(sqlalchemy.text(CREATE_AUTHORS), [{"p1": a.name, "p2": a.bio} for a in arg])
            return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount

    def create_books(self, arg: Sequence[CreateBooksParams]) -> None:
        with errors._wrap_errors("create_books"):
            if not arg:
                return None
            self._conn.execute(sqlalchemy.text(CREATE_BOOKS), [{
                "p1": a.author_id,
                "p2": a.title,
                "p3": a.status,
                "p4": a.from_,
            } for a in arg])

    def delete_author(self, *, id: int) -> int:
        with errors._wrap_errors("delete_author"):
            result = self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})
            return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount

    def get_author(self, *, id: int) -> models.Author | None:
        with errors._wrap_errors("get_author"):
            row = self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id}).first()
            if row is None:
                return None
            return models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
                created_at=cast(pydantic.AwareDatetime, row[3]),
            )

    def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> Iterator[models.Author | None]:
        """Look up several authors at once."""
        with errors._wrap_errors("get_authors_by_id"):
            for a in arg:
                row = self._conn.execute(sqlalchemy.text(GET_AUTHORS_BY_ID), {"p1": a.id}).first()
                if row is None:
                    yield None
                else:
                    yield models.Author(
                        id=cast(int, row[0]),
                        name=cast(str, row[1]),
                        bio=cast(str | None, row[2]),
                        created_at=cast(pydantic.AwareDatetime, row[3]),
                    )

    def get_book_with_author(self, *, id: int) -> GetBookWithAuthorRow | None:
        with errors._wrap_errors("get_book_with_author"):
            row = self._conn.execute(sqlalchemy.text(GET_BOOK_WITH_AUTHOR), {"p1": id}).first()
            if row is None:
                return None
            return GetBookWithAuthorRow(
                books=models.Book(
                    id=cast(int, row[0]),
                    author_id=cast(int, row[1]),
                    title=cast(str, row[2]),
                    status=cast(models.BookStatus, row[3]),
                    from_=cast(datetime.date | None, row[4]),
                    tags=cast(list[str] | None, row[5]),
                ),
                authors=models.Author(
                    id=cast(int, row[6]),
                    name=cast(str, row[7]),
                    bio=cast(str | None, row[8]),
                    created_at=cast(pydantic.AwareDatetime, row[9]),
                ),
            )

    def list_authors(self) -> Iterator[models.Author]:
        with errors._wrap_errors("list_authors"):
            result = self._conn.execute(sqlalchemy.text(LIST_AUTHORS))
            for row in result:
                yield models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                    bio=cast(str | None, row[2]),
                    created_at=cast(pydantic.AwareDatetime, row[3]),
                )

    def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> Iterator[list[models.Book]]:
        with errors._wrap_errors("list_books_by_author"):
            for a in arg:
                yield [models.Book(
                    id=cast(int, row[0]),
                    author_id=cast(int, row[1]),
                    title=cast(str, row[2]),
                    status=cast(models.BookStatus, row[3]),
                    from_=cast(datetime.date | None, row[4]),
                    tags=cast(list[str] | None, row[5]),
                ) for row in self._conn.execute(sqlalchemy.text(LIST_BOOKS_BY_AUTHOR), {"p1": a.author_id})]

    def list_books_by_status(self, *, status: models.BookStatus, class_: int) -> Iterator[ListBooksByStatusRow]:
        with errors._wrap_errors("list_books_by_status"):
            result = self._conn.execute(sqlalchemy.text(LIST_BOOKS_BY_STATUS), {"p1": status, "p2": class_})
            for row in result:
                yield ListBooksByStatusRow(
                    id=cast(int, row[0]),
                    title=cast(str, row[1]),
                    from_=cast(datetime.date | None, row[2]),
                    author_name=cast(str, row[3]),
                )


class AsyncQuerier[T: sqlalchemy.ext.asyncio.AsyncConnection | sqlalchemy.ext.asyncio.AsyncSession]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    async def count_authors(self) -> int | None:
        with errors._wrap_errors("count_authors"):
            row = (await self._conn.execute(sqlalchemy.text(COUNT_AUTHORS))).first()
            if row is None:
                return None
            return cast(int, row[0])

    async def create_author(self, *, name: str, bio: str | None) -> models.Author | None:
        """Create one author."""
        with errors._wrap_errors("create_author"):
            row = (await self._conn.execute(sqlalchemy.text(CREATE_AUTHOR), {"p1": name, "p2": bio})).first()
            if row is None:
                return None
            return models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
                created_at=cast(pydantic.AwareDatetime, row[3]),
            )

    async def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int:
        with errors._wrap_errors("create_authors"):
            if not arg:
                return 0
            result = await self._conn.execute(sqlalchemy.text(CREATE_AUTHORS), [{"p1": a.name, "p2": a.bio} for a in arg])
            return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount

    async def create_books(self, arg: Sequence[CreateBooksParams]) -> None:
        with errors._wrap_errors("create_books"):
            if not arg:
                return None
            await self._conn.execute(sqlalchemy.text(CREATE_BOOKS), [{
                "p1": a.author_id,
                "p2": a.title,
                "p3": a.status,
                "p4": a.from_,
            } for a in arg])

    async def delete_author(self, *, id: int) -> int:
        with errors._wrap_errors("delete_author"):
            result = await self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})
            return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount

    async def get_author(self, *, id: int) -> models.Author | None:
        with errors._wrap_errors("get_author"):
            row = (await self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id})).first()
            if row is None:
                return None
            return models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
                created_at=cast(pydantic.AwareDatetime, row[3]),
            )

    async def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> AsyncIterator[models.Author | None]:
        """Look up several authors at once."""
        with errors._wrap_errors("get_authors_by_id"):
            for a in arg:
                row = (await self._conn.execute(sqlalchemy.text(GET_AUTHORS_BY_ID), {"p1": a.id})).first()
                if row is None:
                    yield None
                else:
                    yield models.Author(
                        id=cast(int, row[0]),
                        name=cast(str, row[1]),
                        bio=cast(str | None, row[2]),
                        created_at=cast(pydantic.AwareDatetime, row[3]),
                    )

    async def get_book_with_author(self, *, id: int) -> GetBookWithAuthorRow | None:
        with errors._wrap_errors("get_book_with_author"):
            row = (await self._conn.execute(sqlalchemy.text(GET_BOOK_WITH_AUTHOR), {"p1": id})).first()
            if row is None:
                return None
            return GetBookWithAuthorRow(
                books=models.Book(
                    id=cast(int, row[0]),
                    author_id=cast(int, row[1]),
                    title=cast(str, row[2]),
                    status=cast(models.BookStatus, row[3]),
                    from_=cast(datetime.date | None, row[4]),
                    tags=cast(list[str] | None, row[5]),
                ),
                authors=models.Author(
                    id=cast(int, row[6]),
                    name=cast(str, row[7]),
                    bio=cast(str | None, row[8]),
                    created_at=cast(pydantic.AwareDatetime, row[9]),
                ),
            )

    async def list_authors(self) -> AsyncIterator[models.Author]:
        with errors._wrap_errors("list_authors"):
            result = await self._conn.stream(sqlalchemy.text(LIST_AUTHORS))
            async for row in result:
                yield models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                    bio=cast(str | None, row[2]),
                    created_at=cast(pydantic.AwareDatetime, row[3]),
                )

    async def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> AsyncIterator[list[models.Book]]:
        with errors._wrap_errors("list_books_by_author"):
            for a in arg:
                yield [models.Book(
                    id=cast(int, row[0]),
                    author_id=cast(int, row[1]),
                    title=cast(str, row[2]),
                    status=cast(models.BookStatus, row[3]),
                    from_=cast(datetime.date | None, row[4]),
                    tags=cast(list[str] | None, row[5]),
                ) for row in await self._conn.execute(sqlalchemy.text(LIST_BOOKS_BY_AUTHOR), {"p1": a.author_id})]

    async def list_books_by_status(self, *, status: models.BookStatus, class_: int) -> AsyncIterator[ListBooksByStatusRow]:
        with errors._wrap_errors("list_books_by_status"):
            result = await self._conn.stream(sqlalchemy.text(LIST_BOOKS_BY_STATUS), {"p1": status, "p2": class_})
            async for row in result:
                yield ListBooksByStatusRow(
                    id=cast(int, row[0]),
                    title=cast(str, row[1]),
                    from_=cast(datetime.date | None, row[2]),
                    author_name=cast(str, row[3]),
                )
