# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses


@dataclasses.dataclass()
class Author:
    id: int
    name: str
    bio: str | None


@dataclasses.dataclass()
class Book:
    id: int
    author_id: int
    title: str
