# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import datetime
import pydantic
from typing import List, Optional


class Event(pydantic.BaseModel):
    id: int
    a: pydantic.AwareDatetime
    b: datetime.datetime
    c: Optional[pydantic.AwareDatetime]
    d: Optional[List[pydantic.AwareDatetime]]
