# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import pydantic
from typing import Iterator, Optional

import sqlalchemy

from db import models


GET_LATEST = """-- name: get_latest \\:one
SELECT max(a)\\:\\:timestamptz AS latest FROM events
"""


LIST_EVENTS_SINCE = """-- name: list_events_since \\:many
SELECT id, a, b, c, d FROM events WHERE a > :p1
"""


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def get_latest(self) -> Optional[pydantic.AwareDatetime]:
        row = self._conn.execute(sqlalchemy.text(GET_LATEST)).first()
        if row is None:
            return None
        return row[0]

    def list_events_since(self, *, a: pydantic.AwareDatetime) -> Iterator[models.Event]:
        result = self._conn.execute(sqlalchemy.text(LIST_EVENTS_SINCE), {"p1": a})
        for row in result:
            yield models.Event(
                id=row[0],
                a=row[1],
                b=row[2],
                c=row[3],
                d=row[4],
            )
