# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import datetime
import pydantic
from typing import Iterator, List, Optional, Union, cast

import sqlalchemy
import sqlalchemy.orm

from db import models


GET_LATEST = """-- name: get_latest \\:one
SELECT max(a)\\:\\:timestamptz AS latest FROM events
"""


LIST_EVENTS_SINCE = """-- name: list_events_since \\:many
SELECT id, a, b, c, d FROM events WHERE a > :p1
"""


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def get_latest(self) -> Optional[pydantic.AwareDatetime]:
        row = self._conn.execute(sqlalchemy.text(GET_LATEST)).first()
        if row is None:
            return None
        return cast(pydantic.AwareDatetime, row[0])

    def list_events_since(self, *, a: pydantic.AwareDatetime) -> Iterator[models.Event]:
        result = self._conn.execute(sqlalchemy.text(LIST_EVENTS_SINCE), {"p1": a})
        for row in result:
            yield models.Event(
                id=cast(int, row[0]),
                a=cast(pydantic.AwareDatetime, row[1]),
                b=cast(datetime.datetime, row[2]),
                c=cast(Optional[pydantic.AwareDatetime], row[3]),
                d=cast(Optional[List[pydantic.AwareDatetime]], row[4]),
            )
