# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses
import datetime
import enum
from typing import Any


class Status(str, enum.Enum):
    DRAFT = "draft"
    PUBLISHED = "published"


@dataclasses.dataclass()
class Post:
    id: int
    title: str
    tags: list[str] | None
    status: Status | None
    payload: Any | None
    created_at: datetime.datetime
