# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import dataclasses
import datetime
from collections.abc import AsyncIterator, Iterator
from typing import Any, cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from db import models


CREATE_POST = """-- name: create_post \\:one
INSERT INTO posts (title, tags, status, created_at) VALUES (:p1, :p2, :p3, :p4)
RETURNING id, title, tags, status, payload, created_at
"""


GET_POST = """-- name: get_post \\:one
SELECT id, title, tags, status, payload, created_at FROM posts WHERE id = :p1
"""


LIST_POSTS = """-- name: list_posts \\:many
SELECT id, title, tags, status, payload, created_at FROM posts ORDER BY id
"""


LIST_TITLES = """-- name: list_titles \\:many
SELECT id, title FROM posts WHERE status = :p1
"""


@dataclasses.dataclass()
class ListTitlesRow:
    id: int
    title: str


class Querier:
    _conn: sqlalchemy.engine.Connection | sqlalchemy.orm.Session

    def __init__(self, conn: sqlalchemy.engine.Connection | sqlalchemy.orm.Session):
        self._conn = conn

    def create_post(self, *, title: str, tags: list[str] | None, status: models.Status | None, created_at: datetime.datetime) -> models.Post | None:
        row = self._conn.execute(sqlalchemy.text(CREATE_POST), {
            "p1": title,
            "p2": tags,
            "p3": status,
            "p4": created_at,
        }).first()
        if row is None:
            return None
        return models.Post(
            id=cast(int, row[0]),
            title=cast(str, row[1]),
            tags=cast(list[str] | None, row[2]),
            status=cast(models.Status | None, row[3]),
            payload=cast(Any | None, row[4]),
            created_at=cast(datetime.datetime, row[5]),
        )

    def get_post(self, *, id: int) -> models.Post | None:
        row = self._conn.execute(sqlalchemy.text(GET_POST), {"p1": id}).first()
        if row is None:
            return None
        return models.Post(
            id=cast(int, row[0]),
            title=cast(str, row[1]),
            tags=cast(list[str] | None, row[2]),
            status=cast(models.Status | None, row[3]),
            payload=cast(Any | None, row[4]),
            created_at=cast(datetime.datetime, row[5]),
        )

    def list_posts(self) -> Iterator[models.Post]:
        result = self._conn.execute(sqlalchemy.text(LIST_POSTS))
        for row in result:
            yield models.Post(
                id=cast(int, row[0]),
                title=cast(str, row[1]),
                tags=cast(list[str] | None, row[2]),
                status=cast(models.Status | None, row[3]),
                payload=cast(Any | None, row[4]),
                created_at=cast(datetime.datetime, row[5]),
            )

    def list_titles(self, *, status: models.Status | None) -> Iterator[ListTitlesRow]:
        result = self._conn.execute(sqlalchemy.text(LIST_TITLES), {"p1": status})
        for row in result:
            yield ListTitlesRow(
                id=cast(int, row[0]),
                title=cast(str, row[1]),
            )


class AsyncQuerier:
    _conn: sqlalchemy.ext.asyncio.AsyncConnection | sqlalchemy.ext.asyncio.AsyncSession

    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection | sqlalchemy.ext.asyncio.AsyncSession):
        self._conn = conn

    async def create_post(self, *, title: str, tags: list[str] | None, status: models.Status | None, created_at: datetime.datetime) -> models.Post | None:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_POST), {
            "p1": title,
            "p2": tags,
            "p3": status,
            "p4": created_at,
        })).first()
        if row is None:
            return None
        return models.Post(
            id=cast(int, row[0]),
            title=cast(str, row[1]),
            tags=cast(list[str] | None, row[2]),
            status=cast(models.Status | None, row[3]),
            payload=cast(Any | None, row[4]),
            created_at=cast(datetime.datetime, row[5]),
        )

    async def get_post(self, *, id: int) -> models.Post | None:
        row = (await self._conn.execute(sqlalchemy.text(GET_POST), {"p1": id})).first()
        if row is None:
            return None
        return models.Post(
            id=cast(int, row[0]),
            title=cast(str, row[1]),
            tags=cast(list[str] | None, row[2]),
            status=cast(models.Status | None, row[3]),
            payload=cast(Any | None, row[4]),
            created_at=cast(datetime.datetime, row[5]),
        )

    async def list_posts(self) -> AsyncIterator[models.Post]:
        result = await self._conn.stream(sqlalchemy.text(LIST_POSTS))
        async for row in result:
            yield models.Post(
                id=cast(int, row[0]),
                title=cast(str, row[1]),
                tags=cast(list[str] | None, row[2]),
                status=cast(models.Status | None, row[3]),
                payload=cast(Any | None, row[4]),
                created_at=cast(datetime.datetime, row[5]),
            )

    async def list_titles(self, *, status: models.Status | None) -> AsyncIterator[ListTitlesRow]:
        result = await self._conn.stream(sqlalchemy.text(LIST_TITLES), {"p1": status})
        async for row in result:
            yield ListTitlesRow(
                id=cast(int, row[0]),
                title=cast(str, row[1]),
            )
