# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
from typing import AsyncIterator, Iterator, Optional, Union, cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from db import models


DELETE_AUTHOR = """-- name: delete_author \\:exec
DELETE FROM authors WHERE id = :p1
"""


GET_AUTHOR = """-- name: get_author \\:one
SELECT id, name, bio FROM authors WHERE id = :p1
"""


LIST_AUTHORS = """-- name: list_authors \\:many
SELECT id, name, bio FROM authors ORDER BY name
"""


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def delete_author(self, *, id: int) -> None:
        self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})

    def get_author(self, *, id: int) -> Optional[models.Author]:
        """Fetch an author by id."""
        row = self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id}).first()
        if row is None:
            return None
        return models.Author(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            bio=cast(Optional[str], row[2]),
        )

    def list_authors(self) -> Iterator[models.Author]:
        """List every author.
Ordered by "name", with a \\ backslash."""
        result = self._conn.execute(sqlalchemy.text(LIST_AUTHORS))
        for row in result:
            yield models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(Optional[str], row[2]),
            )


class AsyncQuerier:
    _conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]

    def __init__(self, conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]):
        self._conn = conn

    async def delete_author(self, *, id: int) -> None:
        await self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})

    async def get_author(self, *, id: int) -> Optional[models.Author]:
        """Fetch an author by id."""
        row = (await self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id})).first()
        if row is None:
            return None
        return models.Author(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            bio=cast(Optional[str], row[2]),
        )

    async def list_authors(self) -> AsyncIterator[models.Author]:
        """List every author.
Ordered by "name", with a \\ backslash."""
        result = await self._conn.stream(sqlalchemy.text(LIST_AUTHORS))
        async for row in result:
            yield models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(Optional[str], row[2]),
            )
