# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses
from typing import Optional


@dataclasses.dataclass()
class Author:
    id: int
    name: str


@dataclasses.dataclass()
class Book:
    id: int
    author_id: int
    title: str
    isbn: Optional[str]
