# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import dataclasses
from typing import AsyncIterator, Iterator, Optional, Union, cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from dc import models


GET_AUTHOR_ONLY = """-- name: get_author_only \\:one
SELECT authors.id, authors.name FROM authors WHERE id = :p1
"""


@dataclasses.dataclass()
class GetAuthorOnlyRow:
    authors: models.Author


GET_BOOK_WITH_AUTHOR = """-- name: get_book_with_author \\:one
SELECT authors.id, authors.name, books.title
FROM authors JOIN books ON books.author_id = authors.id
WHERE books.id = :p1
"""


@dataclasses.dataclass()
class GetBookWithAuthorRow:
    authors: models.Author
    title: str


LIST_AUTHORS_AND_BOOKS = """-- name: list_authors_and_books \\:many
SELECT authors.id, authors.name, books.id, books.author_id, books.title, books.isbn
FROM authors JOIN books ON books.author_id = authors.id
"""


@dataclasses.dataclass()
class ListAuthorsAndBooksRow:
    authors: models.Author
    books: models.Book


LIST_TITLES_WITH_AUTHOR = """-- name: list_titles_with_author \\:many
SELECT books.id, authors.id, authors.name, books.title
FROM books JOIN authors ON books.author_id = authors.id
"""


@dataclasses.dataclass()
class ListTitlesWithAuthorRow:
    id: int
    authors: models.Author
    title: str


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def get_author_only(self, *, id: int) -> Optional[GetAuthorOnlyRow]:
        row = self._conn.execute(sqlalchemy.text(GET_AUTHOR_ONLY), {"p1": id}).first()
        if row is None:
            return None
        return GetAuthorOnlyRow(
            authors=models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
            ),
        )

    def get_book_with_author(self, *, id: int) -> Optional[GetBookWithAuthorRow]:
        row = self._conn.execute(sqlalchemy.text(GET_BOOK_WITH_AUTHOR), {"p1": id}).first()
        if row is None:
            return None
        return GetBookWithAuthorRow(
            authors=models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
            ),
            title=cast(str, row[2]),
        )

    def list_authors_and_books(self) -> Iterator[ListAuthorsAndBooksRow]:
        result = self._conn.execute(sqlalchemy.text(LIST_AUTHORS_AND_BOOKS))
        for row in result:
            yield ListAuthorsAndBooksRow(
                authors=models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                ),
                books=models.Book(
                    id=cast(int, row[2]),
                    author_id=cast(int, row[3]),
                    title=cast(str, row[4]),
                    isbn=cast(Optional[str], row[5]),
                ),
            )

    def list_titles_with_author(self) -> Iterator[ListTitlesWithAuthorRow]:
        result = self._conn.execute(sqlalchemy.text(LIST_TITLES_WITH_AUTHOR))
        for row in result:
            yield ListTitlesWithAuthorRow(
                id=cast(int, row[0]),
                authors=models.Author(
                    id=cast(int, row[1]),
                    name=cast(str, row[2]),
                ),
                title=cast(str, row[3]),
            )


class AsyncQuerier:
    _conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]

    def __init__(self, conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]):
        self._conn = conn

    async def get_author_only(self, *, id: int) -> Optional[GetAuthorOnlyRow]:
        row = (await self._conn.execute(sqlalchemy.text(GET_AUTHOR_ONLY), {"p1": id})).first()
        if row is None:
            return None
        return GetAuthorOnlyRow(
            authors=models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
            ),
        )

    async def get_book_with_author(self, *, id: int) -> Optional[GetBookWithAuthorRow]:
        row = (await self._conn.execute(sqlalchemy.text(GET_BOOK_WITH_AUTHOR), {"p1": id})).first()
        if row is None:
            return None
        return GetBookWithAuthorRow(
            authors=models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
            ),
            title=cast(str, row[2]),
        )

    async def list_authors_and_books(self) -> AsyncIterator[ListAuthorsAndBooksRow]:
        result = await self._conn.stream(sqlalchemy.text(LIST_AUTHORS_AND_BOOKS))
        async for row in result:
            yield ListAuthorsAndBooksRow(
                authors=models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                ),
                books=models.Book(
                    id=cast(int, row[2]),
                    author_id=cast(int, row[3]),
                    title=cast(str, row[4]),
                    isbn=cast(Optional[str], row[5]),
                ),
            )

    async def list_titles_with_author(self) -> AsyncIterator[ListTitlesWithAuthorRow]:
        result = await self._conn.stream(sqlalchemy.text(LIST_TITLES_WITH_AUTHOR))
        async for row in result:
            yield ListTitlesWithAuthorRow(
                id=cast(int, row[0]),
                authors=models.Author(
                    id=cast(int, row[1]),
                    name=cast(str, row[2]),
                ),
                title=cast(str, row[3]),
            )
