# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses
import enum


class Priority(str, enum.Enum):
    LOW = "low"
    HIGH = "high"


class Status(str, enum.Enum):
    ACTIVE = "active"
    RETIRED = "retired"


@dataclasses.dataclass()
class Author:
    id: int
    name: str
    status: Status
