# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import dataclasses
from typing import Iterator, Optional

import sqlalchemy

from db import models


GET_AUTHOR = """-- name: get_author \\:one
SELECT id, name, status FROM authors WHERE id = :p1
"""


LIST_TASK_TITLES = """-- name: list_task_titles \\:many
SELECT id, title FROM tasks WHERE priority = :p1
"""


@dataclasses.dataclass()
class ListTaskTitlesRow:
    id: int
    title: str


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def get_author(self, *, id: int) -> Optional[models.Author]:
        row = self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id}).first()
        if row is None:
            return None
        return models.Author(
            id=row[0],
            name=row[1],
            status=row[2],
        )

    def list_task_titles(self, *, priority: models.Priority) -> Iterator[ListTaskTitlesRow]:
        result = self._conn.execute(sqlalchemy.text(LIST_TASK_TITLES), {"p1": priority})
        for row in result:
            yield ListTaskTitlesRow(
                id=row[0],
                title=row[1],
            )
