# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import dataclasses
from typing import Any, AsyncIterator, Iterator, List, Optional, Protocol, Sequence, Union, cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from db import models


CREATE_AUTHORS = """-- name: create_authors \\:copyfrom
INSERT INTO authors (name, bio) VALUES (:p1, :p2)
"""


@dataclasses.dataclass()
class CreateAuthorsParams:
    name: str
    bio: Optional[str]


DELETE_AUTHOR = """-- name: delete_author \\:exec
DELETE FROM authors WHERE id = :p1
"""


GET_AUTHOR = """-- name: get_author \\:one
SELECT id, name, bio FROM authors WHERE id = :p1
"""


GET_AUTHORS_BY_ID = """-- name: get_authors_by_id \\:batchone
SELECT id, name, bio FROM authors WHERE id = :p1
"""


@dataclasses.dataclass()
class GetAuthorsByIDParams:
    id: int


LIST_AUTHORS = """-- name: list_authors \\:many
SELECT id, name, bio FROM authors ORDER BY name
"""


LIST_BOOKS_BY_AUTHOR = """-- name: list_books_by_author \\:batchmany
SELECT id, author_id, title FROM books WHERE author_id = :p1
"""


@dataclasses.dataclass()
class ListBooksByAuthorParams:
    author_id: int


class QuerierProtocol(Protocol):
    def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int: ...

    def delete_author(self, *, id: int) -> None: ...

    def get_author(self, *, id: int) -> Optional[models.Author]: ...

    def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> Iterator[Optional[models.Author]]: ...

    def list_authors(self) -> Iterator[models.Author]: ...

    def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> Iterator[List[models.Book]]: ...


class AsyncQuerierProtocol(Protocol):
    async def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int: ...

    async def delete_author(self, *, id: int) -> None: ...

    async def get_author(self, *, id: int) -> Optional[models.Author]: ...

    def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> AsyncIterator[Optional[models.Author]]: ...

    def list_authors(self) -> AsyncIterator[models.Author]: ...

    def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> AsyncIterator[List[models.Book]]: ...


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int:
        if not arg:
            return 0
        result = self._conn.execute(sqlalchemy.text(CREATE_AUTHORS), [{"p1": a.name, "p2": a.bio} for a in arg])
        return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount

    def delete_author(self, *, id: int) -> None:
        self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})

    def get_author(self, *, id: int) -> Optional[models.Author]:
        row = self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id}).first()
        if row is None:
            return None
        return models.Author(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            bio=cast(Optional[str], row[2]),
        )

    def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> Iterator[Optional[models.Author]]:
        for a in arg:
            row = self._conn.execute(sqlalchemy.text(GET_AUTHORS_BY_ID), {"p1": a.id}).first()
            if row is None:
                yield None
            else:
                yield models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                    bio=cast(Optional[str], row[2]),
                )

    def list_authors(self) -> Iterator[models.Author]:
        result = self._conn.execute(sqlalchemy.text(LIST_AUTHORS))
        for row in result:
            yield models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(Optional[str], row[2]),
            )

    def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> Iterator[List[models.Book]]:
        for a in arg:
            yield [models.Book(
                id=cast(int, row[0]),
                author_id=cast(int, row[1]),
                title=cast(str, row[2]),
            ) for row in self._conn.execute(sqlalchemy.text(LIST_BOOKS_BY_AUTHOR), {"p1": a.author_id})]


class AsyncQuerier:
    _conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]

    def __init__(self, conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]):
        self._conn = conn

    async def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> int:
        if not arg:
            return 0
        result = await self._conn.execute(sqlalchemy.text(CREATE_AUTHORS), [{"p1": a.name, "p2": a.bio} for a in arg])
        return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount

    async def delete_author(self, *, id: int) -> None:
        await self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})

    async def get_author(self, *, id: int) -> Optional[models.Author]:
        row = (await self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id})).first()
        if row is None:
            return None
        return models.Author(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            bio=cast(Optional[str], row[2]),
        )

    async def get_authors_by_id(self, arg: Sequence[GetAuthorsByIDParams]) -> AsyncIterator[Optional[models.Author]]:
        for a in arg:
            row = (await self._conn.execute(sqlalchemy.text(GET_AUTHORS_BY_ID), {"p1": a.id})).first()
            if row is None:
                yield None
            else:
                yield models.Author(
                    id=cast(int, row[0]),
                    name=cast(str, row[1]),
                    bio=cast(Optional[str], row[2]),
                )

    async def list_authors(self) -> AsyncIterator[models.Author]:
        result = await self._conn.stream(sqlalchemy.text(LIST_AUTHORS))
        async for row in result:
            yield models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(Optional[str], row[2]),
            )

    async def list_books_by_author(self, arg: Sequence[ListBooksByAuthorParams]) -> AsyncIterator[List[models.Book]]:
        for a in arg:
            yield [models.Book(
                id=cast(int, row[0]),
                author_id=cast(int, row[1]),
                title=cast(str, row[2]),
            ) for row in await self._conn.execute(sqlalchemy.text(LIST_BOOKS_BY_AUTHOR), {"p1": a.author_id})]
