# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import dataclasses
from typing import Iterator, Optional

import sqlalchemy

from db import models


COUNT_AUTHORS = """-- name: count_authors \\:one
SELECT count(*) FROM authors
"""


@dataclasses.dataclass()
class CountAuthorsParams:
    pass


LIST_AUTHORS = """-- name: list_authors \\:many
SELECT id, name FROM authors
"""


@dataclasses.dataclass()
class ListAuthorsParams:
    pass


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def count_authors(self, arg: CountAuthorsParams) -> Optional[int]:
        row = self._conn.execute(sqlalchemy.text(COUNT_AUTHORS)).first()
        if row is None:
            return None
        return row[0]

    def list_authors(self, arg: ListAuthorsParams) -> Iterator[models.Author]:
        result = self._conn.execute(sqlalchemy.text(LIST_AUTHORS))
        for row in result:
            yield models.Author(
                id=row[0],
                name=row[1],
            )
