# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import dataclasses
from typing import AsyncIterator, Iterator, Optional, Union, cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from db import models


GET_TRIP = """-- name: get_trip \\:one
SELECT id, "from", "to", class FROM trips
WHERE id = :p1 LIMIT 1
"""


IMPORT = """-- name: import_ \\:exec
INSERT INTO trips ("from", "to", class) VALUES (:p1, :p2, :p3)
"""


LIST_DEPARTURES = """-- name: list_departures \\:many
SELECT id, "from" FROM trips
WHERE class = :p1
"""


@dataclasses.dataclass()
class ListDeparturesRow:
    id: int
    from_: str


LIST_TRIPS_BY_CLASS = """-- name: list_trips_by_class \\:many
SELECT id, "from", "to", class FROM trips
WHERE class = :p1
"""


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def get_trip(self, *, id: int) -> Optional[models.Trip]:
        row = self._conn.execute(sqlalchemy.text(GET_TRIP), {"p1": id}).first()
        if row is None:
            return None
        return models.Trip(
            id=cast(int, row[0]),
            from_=cast(str, row[1]),
            to=cast(str, row[2]),
            class_=cast(str, row[3]),
        )

    def import_(self, *, from_: str, to: str, class_: str) -> None:
        self._conn.execute(sqlalchemy.text(IMPORT), {"p1": from_, "p2": to, "p3": class_})

    def list_departures(self, *, class_: str) -> Iterator[ListDeparturesRow]:
        result = self._conn.execute(sqlalchemy.text(LIST_DEPARTURES), {"p1": class_})
        for row in result:
            yield ListDeparturesRow(
                id=cast(int, row[0]),
                from_=cast(str, row[1]),
            )

    def list_trips_by_class(self, *, class_: str) -> Iterator[models.Trip]:
        result = self._conn.execute(sqlalchemy.text(LIST_TRIPS_BY_CLASS), {"p1": class_})
        for row in result:
            yield models.Trip(
                id=cast(int, row[0]),
                from_=cast(str, row[1]),
                to=cast(str, row[2]),
                class_=cast(str, row[3]),
            )


class AsyncQuerier:
    _conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]

    def __init__(self, conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]):
        self._conn = conn

    async def get_trip(self, *, id: int) -> Optional[models.Trip]:
        row = (await self._conn.execute(sqlalchemy.text(GET_TRIP), {"p1": id})).first()
        if row is None:
            return None
        return models.Trip(
            id=cast(int, row[0]),
            from_=cast(str, row[1]),
            to=cast(str, row[2]),
            class_=cast(str, row[3]),
        )

    async def import_(self, *, from_: str, to: str, class_: str) -> None:
        await self._conn.execute(sqlalchemy.text(IMPORT), {"p1": from_, "p2": to, "p3": class_})

    async def list_departures(self, *, class_: str) -> AsyncIterator[ListDeparturesRow]:
        result = await self._conn.stream(sqlalchemy.text(LIST_DEPARTURES), {"p1": class_})
        async for row in result:
            yield ListDeparturesRow(
                id=cast(int, row[0]),
                from_=cast(str, row[1]),
            )

    async def list_trips_by_class(self, *, class_: str) -> AsyncIterator[models.Trip]:
        result = await self._conn.stream(sqlalchemy.text(LIST_TRIPS_BY_CLASS), {"p1": class_})
        async for row in result:
            yield models.Trip(
                id=cast(int, row[0]),
                from_=cast(str, row[1]),
                to=cast(str, row[2]),
                class_=cast(str, row[3]),
            )
