# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
from collections.abc import AsyncIterator, Iterator
from typing import Any, Protocol, cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from modern import models


DELETE_AUTHOR = """-- name: delete_author \\:execrows
DELETE FROM authors WHERE id = :p1
"""


GET_AUTHOR = """-- name: get_author \\:one
SELECT id, name, bio FROM authors WHERE id = :p1
"""


LIST_AUTHORS = """-- name: list_authors \\:many
SELECT id, name, bio FROM authors ORDER BY name
"""


T = """-- name: t \\:one
SELECT name FROM authors WHERE id = :p1
"""


class QuerierProtocol(Protocol):
    def delete_author(self, *, id: int) -> int: ...

    def get_author(self, *, id: int) -> models.Author | None: ...

    def list_authors(self) -> Iterator[models.Author]: ...

    def t(self, *, id: int) -> str | None: ...


class AsyncQuerierProtocol(Protocol):
    async def delete_author(self, *, id: int) -> int: ...

    async def get_author(self, *, id: int) -> models.Author | None: ...

    def list_authors(self) -> AsyncIterator[models.Author]: ...

    async def t(self, *, id: int) -> str | None: ...


class Querier[_ConnT: sqlalchemy.engine.Connection | sqlalchemy.orm.Session]:
    _conn: _ConnT

    def __init__(self, conn: _ConnT):
        self._conn = conn

    def delete_author(self, *, id: int) -> int:
        result = self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})
        return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount

    def get_author(self, *, id: int) -> models.Author | None:
        row = self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id}).first()
        if row is None:
            return None
        return models.Author(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            bio=cast(str | None, row[2]),
        )

    def list_authors(self) -> Iterator[models.Author]:
        result = self._conn.execute(sqlalchemy.text(LIST_AUTHORS))
        for row in result:
            yield models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
            )

    def t(self, *, id: int) -> str | None:
        row = self._conn.execute(sqlalchemy.text(T), {"p1": id}).first()
        if row is None:
            return None
        return cast(str, row[0])


class AsyncQuerier[_ConnT: sqlalchemy.ext.asyncio.AsyncConnection | sqlalchemy.ext.asyncio.AsyncSession]:
    _conn: _ConnT

    def __init__(self, conn: _ConnT):
        self._conn = conn

    async def delete_author(self, *, id: int) -> int:
        result = await self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})
        return cast("sqlalchemy.engine.CursorResult[Any]", result).rowcount

    async def get_author(self, *, id: int) -> models.Author | None:
        row = (await self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id})).first()
        if row is None:
            return None
        return models.Author(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            bio=cast(str | None, row[2]),
        )

    async def list_authors(self) -> AsyncIterator[models.Author]:
        result = await self._conn.stream(sqlalchemy.text(LIST_AUTHORS))
        async for row in result:
            yield models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
            )

    async def t(self, *, id: int) -> str | None:
        row = (await self._conn.execute(sqlalchemy.text(T), {"p1": id})).first()
        if row is None:
            return None
        return cast(str, row[0])
