# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses
import datetime
import enum
from typing import List, Optional


class BookStatus(str, enum.Enum):
    """Lifecycle of a book.
"Out of print" books stay listed."""
    DRAFT = "draft"
    IN_PRINT = "in-print"
    OUT_OF_PRINT = "out_of_print"
    VALUE_4 = "="


@dataclasses.dataclass()
class Author:
    """People who write books."""
    id: int
    name: str
    bio: Optional[str]
    created_at: datetime.datetime


@dataclasses.dataclass()
class Book:
    id: int
    author_id: int
    title: str
    status: BookStatus
    # First published.
    # NULL until the book is released.
    from_: Optional[datetime.date]
    tags: Optional[List[str]]
