# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
import dataclasses
import enum
from typing import Optional


class MusicGenre(str, enum.Enum):
    ROCK = "rock"
    HIP_HOP_MUSIC = "hip-hop"


@dataclasses.dataclass()
class Artist:
    id: int
    spotify_link: Optional[str]
    kind: MusicGenre


@dataclasses.dataclass()
class Human:
    id: int
    name: str
    category: str
