# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import dataclasses
from typing import Iterator, Optional, Union, cast

import sqlalchemy
import sqlalchemy.orm

from db import models


GET_ARTIST = """-- name: get_artist \\:one
SELECT id, spotify_url, kind FROM artists WHERE spotify_url = :p1
"""


GET_PERSON = """-- name: get_person \\:one
SELECT id, name, class FROM people WHERE id = :p1
"""


LIST_ARTIST_LINKS = """-- name: list_artist_links \\:many
SELECT id, spotify_url FROM artists WHERE kind = :p1
"""


@dataclasses.dataclass()
class ListArtistLinksRow:
    id: int
    spotify_link: Optional[str]


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def get_artist(self, *, spotify_link: Optional[str]) -> Optional[models.Artist]:
        row = self._conn.execute(sqlalchemy.text(GET_ARTIST), {"p1": spotify_link}).first()
        if row is None:
            return None
        return models.Artist(
            id=cast(int, row[0]),
            spotify_link=cast(Optional[str], row[1]),
            kind=cast(models.MusicGenre, row[2]),
        )

    def get_person(self, *, id: int) -> Optional[models.Human]:
        row = self._conn.execute(sqlalchemy.text(GET_PERSON), {"p1": id}).first()
        if row is None:
            return None
        return models.Human(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            category=cast(str, row[2]),
        )

    def list_artist_links(self, *, kind: models.MusicGenre) -> Iterator[ListArtistLinksRow]:
        result = self._conn.execute(sqlalchemy.text(LIST_ARTIST_LINKS), {"p1": kind})
        for row in result:
            yield ListArtistLinksRow(
                id=cast(int, row[0]),
                spotify_link=cast(Optional[str], row[1]),
            )
