# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
# source: query.sql
import dataclasses
from typing import Optional, Sequence, Union

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from db import models


CREATE_AUTHORS = """-- name: create_authors \\:batchexec
INSERT INTO authors (name, bio) VALUES (:p1, :p2)
"""


@dataclasses.dataclass()
class CreateAuthorsParams:
    name: str
    bio: Optional[str]


DELETE_AUTHORS = """-- name: delete_authors \\:batchexec
DELETE FROM authors WHERE id = :p1
"""


@dataclasses.dataclass()
class DeleteAuthorsParams:
    id: int


class Querier:
    _conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]

    def __init__(self, conn: Union[sqlalchemy.engine.Connection, sqlalchemy.orm.Session]):
        self._conn = conn

    def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> None:
        if not arg:
            return None
        self._conn.execute(sqlalchemy.text(CREATE_AUTHORS), [{"p1": a.name, "p2": a.bio} for a in arg])

    def delete_authors(self, arg: Sequence[DeleteAuthorsParams]) -> None:
        if not arg:
            return None
        self._conn.execute(sqlalchemy.text(DELETE_AUTHORS), [{"p1": a.id} for a in arg])


class AsyncQuerier:
    _conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]

    def __init__(self, conn: Union[sqlalchemy.ext.asyncio.AsyncConnection, sqlalchemy.ext.asyncio.AsyncSession]):
        self._conn = conn

    async def create_authors(self, arg: Sequence[CreateAuthorsParams]) -> None:
        if not arg:
            return None
        await self._conn.execute(sqlalchemy.text(CREATE_AUTHORS), [{"p1": a.name, "p2": a.bio} for a in arg])

    async def delete_authors(self, arg: Sequence[DeleteAuthorsParams]) -> None:
        if not arg:
            return None
        await self._conn.execute(sqlalchemy.text(DELETE_AUTHORS), [{"p1": a.id} for a in arg])
